#!/bin/bash

rm -fr $HOME/.THE_BOWER_STUFF

mv ./resources/bower $HOME/.THE_BOWER_STUFF



cat .npmignore | grep -e \^\!resources | while read FILE; do

    # convert !resources/bower/async/lib/async.js into async/lib/async.js
    PART=${FILE#\!resources/bower/}

    # source = $HOME/.THE_BOWER_STUFF/ + async/lib/async.js
    SOURCE=$HOME/.THE_BOWER_STUFF/$PART

    # destination = ./resources/bower/ + async/lib/async.js
    DESTINATION=./resources/bower/$PART
    
    echo copy $SOURCE to $DESTINATION

    DIR=`dirname $DESTINATION`

    mkdir -p $DIR

    cp -v $SOURCE $DESTINATION

done
